#include "asset_manager.hpp"

#include "catalog_schema.hpp"  // generated by CMake from schema/catalog.sql
#include "tiff_reader.hpp"

#include <sqlite3.h>

#include <algorithm>
#include <array>
#include <cctype>
#include <chrono>
#include <cstdio>
#include <cstring>
#include <filesystem>
#include <fstream>
#include <memory>
#include <random>
#include <set>
#include <stdexcept>
#include <string_view>
#include <type_traits>

namespace darkhouse {
namespace {

namespace fs = std::filesystem;

constexpr int kBusyTimeoutMs = 5000;

template <class... Fs>
struct Overloaded : Fs... {
    using Fs::operator()...;
};
template <class... Fs>
Overloaded(Fs...) -> Overloaded<Fs...>;

// -----------------------------------------------------------------------------
// SQLite helpers
// -----------------------------------------------------------------------------

struct StatementDeleter {
    void operator()(sqlite3_stmt* stmt) const noexcept { sqlite3_finalize(stmt); }
};
using Statement = std::unique_ptr<sqlite3_stmt, StatementDeleter>;

[[noreturn]] void throwSqlite(sqlite3* db, std::string_view context) {
    throw std::runtime_error(std::string(context) + ": " + (db ? sqlite3_errmsg(db) : "out of memory"));
}

void exec(sqlite3* db, const char* sql) {
    char* error = nullptr;
    if (sqlite3_exec(db, sql, nullptr, nullptr, &error) != SQLITE_OK) {
        const std::string message = error ? error : sqlite3_errmsg(db);
        sqlite3_free(error);
        throw std::runtime_error("sqlite: " + message);
    }
}

bool isBlank(std::string_view text) {
    return std::all_of(text.begin(), text.end(), [](unsigned char c) { return std::isspace(c) != 0; });
}

Statement prepare(sqlite3* db, std::string_view sql) {
    sqlite3_stmt* raw = nullptr;
    const char* tail = nullptr;
    if (sqlite3_prepare_v2(db, sql.data(), static_cast<int>(sql.size()), &raw, &tail) != SQLITE_OK) {
        throwSqlite(db, "prepare");
    }
    Statement stmt(raw);
    if (!stmt) throw std::invalid_argument("SQL statement is empty");
    // prepare_v2 compiles only the first statement. Anything left over means the
    // text held more than one statement (for example a filter such as
    // "1); DELETE FROM assets; --"), so reject it rather than run part of it.
    const std::string_view rest(tail, static_cast<std::size_t>(sql.data() + sql.size() - tail));
    if (!isBlank(rest)) throw std::invalid_argument("SQL must contain exactly one statement");
    return stmt;
}

void stepDone(sqlite3_stmt* stmt, sqlite3* db, std::string_view context) {
    if (sqlite3_step(stmt) != SQLITE_DONE) throwSqlite(db, context);
}

void checkBind(int rc, sqlite3* db) {
    if (rc != SQLITE_OK) throwSqlite(db, "bind");
}

void bindText(sqlite3_stmt* s, int index, std::string_view text) {
    checkBind(sqlite3_bind_text(s, index, text.data(), static_cast<int>(text.size()), SQLITE_TRANSIENT),
              sqlite3_db_handle(s));
}

void bindInt64(sqlite3_stmt* s, int index, std::int64_t value) {
    checkBind(sqlite3_bind_int64(s, index, value), sqlite3_db_handle(s));
}

void bindDouble(sqlite3_stmt* s, int index, double value) {
    checkBind(sqlite3_bind_double(s, index, value), sqlite3_db_handle(s));
}

void bindNull(sqlite3_stmt* s, int index) {
    checkBind(sqlite3_bind_null(s, index), sqlite3_db_handle(s));
}

void bindBlob(sqlite3_stmt* s, int index, const std::vector<std::byte>& blob) {
    // A null pointer would bind SQL NULL, so an empty blob needs a real address.
    static const std::byte kEmpty{};
    const void* data = blob.empty() ? static_cast<const void*>(&kEmpty) : blob.data();
    checkBind(sqlite3_bind_blob(s, index, data, static_cast<int>(blob.size()), SQLITE_TRANSIENT),
              sqlite3_db_handle(s));
}

template <class T>
void bindOptional(sqlite3_stmt* s, int index, const std::optional<T>& value) {
    if (!value) {
        bindNull(s, index);
    } else if constexpr (std::is_same_v<T, std::string>) {
        bindText(s, index, *value);
    } else if constexpr (std::is_floating_point_v<T>) {
        bindDouble(s, index, *value);
    } else {
        bindInt64(s, index, static_cast<std::int64_t>(*value));
    }
}

std::optional<std::string> columnText(sqlite3_stmt* s, int column) {
    if (sqlite3_column_type(s, column) == SQLITE_NULL) return std::nullopt;
    const auto* text = reinterpret_cast<const char*>(sqlite3_column_text(s, column));
    return std::string(text ? text : "", static_cast<std::size_t>(sqlite3_column_bytes(s, column)));
}

std::optional<std::int64_t> columnInt64(sqlite3_stmt* s, int column) {
    if (sqlite3_column_type(s, column) == SQLITE_NULL) return std::nullopt;
    return sqlite3_column_int64(s, column);
}

std::optional<double> columnDouble(sqlite3_stmt* s, int column) {
    if (sqlite3_column_type(s, column) == SQLITE_NULL) return std::nullopt;
    return sqlite3_column_double(s, column);
}

// Rolls back unless commit() succeeds.
class Transaction {
public:
    explicit Transaction(sqlite3* db) : db_(db) { exec(db_, "BEGIN IMMEDIATE"); }
    ~Transaction() {
        if (db_) sqlite3_exec(db_, "ROLLBACK", nullptr, nullptr, nullptr);
    }
    Transaction(const Transaction&) = delete;
    Transaction& operator=(const Transaction&) = delete;

    void commit() {
        exec(db_, "COMMIT");
        db_ = nullptr;
    }

private:
    sqlite3* db_;
};

// Installed on the read connection: user-supplied queryAssets() filters may
// read and call functions, nothing else (no writes, PRAGMA, ATTACH, ...).
int readOnlyAuthorizer(void*, int action, const char*, const char*, const char*, const char*) {
    switch (action) {
    case SQLITE_SELECT:
    case SQLITE_READ:
    case SQLITE_FUNCTION:
    case SQLITE_RECURSIVE:
        return SQLITE_OK;
    default:
        return SQLITE_DENY;
    }
}

// Column order shared by every asset query; readAssetRow() depends on it.
constexpr std::string_view kAssetSelect =
    "SELECT a.id, a.file_path, a.file_name, a.file_hash, a.date_captured, a.date_imported,"
    " a.width, a.height, a.rating, a.color_label, a.flag,"
    " m.camera_make, m.camera_model, m.lens, m.iso, m.focal_length, m.aperture,"
    " m.shutter_speed, m.gps_latitude, m.gps_longitude"
    " FROM assets AS a LEFT JOIN metadata AS m ON m.asset_id = a.id";

AssetRecord readAssetRow(sqlite3_stmt* s) {
    AssetRecord r;
    r.id = columnText(s, 0).value_or("");
    r.filePath = columnText(s, 1).value_or("");
    r.fileName = columnText(s, 2).value_or("");
    r.fileHash = columnText(s, 3).value_or("");
    r.dateCaptured = columnInt64(s, 4);
    r.dateImported = columnInt64(s, 5).value_or(0);
    r.width = static_cast<std::uint32_t>(columnInt64(s, 6).value_or(0));
    r.height = static_cast<std::uint32_t>(columnInt64(s, 7).value_or(0));
    r.rating = static_cast<std::int32_t>(columnInt64(s, 8).value_or(0));
    r.colorLabel = static_cast<ColorLabel>(columnInt64(s, 9).value_or(0));
    r.flag = static_cast<AssetFlag>(columnInt64(s, 10).value_or(0));
    AssetMetadata& m = r.metadata;
    m.cameraMake = columnText(s, 11);
    m.cameraModel = columnText(s, 12);
    m.lens = columnText(s, 13);
    if (auto iso = columnInt64(s, 14)) m.iso = static_cast<std::int32_t>(*iso);
    m.focalLength = columnDouble(s, 15);
    m.aperture = columnDouble(s, 16);
    m.shutterSpeed = columnDouble(s, 17);
    m.gpsLatitude = columnDouble(s, 18);
    m.gpsLongitude = columnDouble(s, 19);
    return r;
}

std::int64_t nowUnixSeconds() {
    return std::chrono::duration_cast<std::chrono::seconds>(std::chrono::system_clock::now().time_since_epoch())
        .count();
}

std::string generateUuidV4() {
    thread_local std::mt19937_64 rng = [] {
        std::random_device device;
        std::seed_seq seed{device(), device(), device(), device(), device(), device(), device(), device()};
        return std::mt19937_64(seed);
    }();
    std::array<std::uint8_t, 16> bytes{};
    for (std::size_t i = 0; i < bytes.size(); i += 8) {
        const std::uint64_t word = rng();
        for (std::size_t b = 0; b < 8; ++b) bytes[i + b] = static_cast<std::uint8_t>(word >> (8 * b));
    }
    bytes[6] = static_cast<std::uint8_t>((bytes[6] & 0x0F) | 0x40);  // version 4
    bytes[8] = static_cast<std::uint8_t>((bytes[8] & 0x3F) | 0x80);  // RFC 4122 variant

    static constexpr char kHex[] = "0123456789abcdef";
    std::string out;
    out.reserve(36);
    for (std::size_t i = 0; i < bytes.size(); ++i) {
        if (i == 4 || i == 6 || i == 8 || i == 10) out.push_back('-');
        out.push_back(kHex[bytes[i] >> 4]);
        out.push_back(kHex[bytes[i] & 0x0F]);
    }
    return out;
}

// -----------------------------------------------------------------------------
// Content fingerprint: streaming XXH64 (seed 0). Fast enough to hash large RAW
// files at disk speed. Collisions are negligible at catalog scale.
// -----------------------------------------------------------------------------

class Xxh64 {
public:
    void update(const std::uint8_t* data, std::size_t size) {
        totalLength_ += size;
        if (bufferSize_ + size < kStripe) {
            std::memcpy(buffer_.data() + bufferSize_, data, size);
            bufferSize_ += size;
            return;
        }
        if (bufferSize_ > 0) {
            const std::size_t fill = kStripe - bufferSize_;
            std::memcpy(buffer_.data() + bufferSize_, data, fill);
            consumeStripe(buffer_.data());
            data += fill;
            size -= fill;
            bufferSize_ = 0;
        }
        for (; size >= kStripe; data += kStripe, size -= kStripe) consumeStripe(data);
        if (size > 0) {
            std::memcpy(buffer_.data(), data, size);
            bufferSize_ = size;
        }
    }

    [[nodiscard]] std::uint64_t digest() const {
        std::uint64_t h;
        if (totalLength_ >= kStripe) {
            h = rotl(v_[0], 1) + rotl(v_[1], 7) + rotl(v_[2], 12) + rotl(v_[3], 18);
            for (const std::uint64_t v : v_) h = mergeRound(h, v);
        } else {
            h = kP5;  // seed + P5 with seed 0
        }
        h += totalLength_;

        const std::uint8_t* p = buffer_.data();
        std::size_t len = bufferSize_;
        for (; len >= 8; p += 8, len -= 8) {
            h ^= mixRound(0, readLE64(p));
            h = rotl(h, 27) * kP1 + kP4;
        }
        if (len >= 4) {
            h ^= static_cast<std::uint64_t>(readLE32(p)) * kP1;
            h = rotl(h, 23) * kP2 + kP3;
            p += 4;
            len -= 4;
        }
        for (; len > 0; ++p, --len) {
            h ^= *p * kP5;
            h = rotl(h, 11) * kP1;
        }
        h ^= h >> 33;
        h *= kP2;
        h ^= h >> 29;
        h *= kP3;
        h ^= h >> 32;
        return h;
    }

private:
    static constexpr std::uint64_t kP1 = 0x9E3779B185EBCA87ULL;
    static constexpr std::uint64_t kP2 = 0xC2B2AE3D27D4EB4FULL;
    static constexpr std::uint64_t kP3 = 0x165667B19E3779F9ULL;
    static constexpr std::uint64_t kP4 = 0x85EBCA77C2B2AE63ULL;
    static constexpr std::uint64_t kP5 = 0x27D4EB2F165667C5ULL;
    static constexpr std::size_t kStripe = 32;

    static std::uint64_t rotl(std::uint64_t x, int r) { return (x << r) | (x >> (64 - r)); }
    static std::uint64_t readLE64(const std::uint8_t* p) {
        std::uint64_t v = 0;
        for (int i = 7; i >= 0; --i) v = (v << 8) | p[i];
        return v;
    }
    static std::uint32_t readLE32(const std::uint8_t* p) {
        return static_cast<std::uint32_t>(p[0]) | (static_cast<std::uint32_t>(p[1]) << 8) |
               (static_cast<std::uint32_t>(p[2]) << 16) | (static_cast<std::uint32_t>(p[3]) << 24);
    }
    static std::uint64_t mixRound(std::uint64_t acc, std::uint64_t input) {
        acc += input * kP2;
        acc = rotl(acc, 31);
        return acc * kP1;
    }
    static std::uint64_t mergeRound(std::uint64_t acc, std::uint64_t value) {
        acc ^= mixRound(0, value);
        return acc * kP1 + kP4;
    }
    void consumeStripe(const std::uint8_t* p) {
        for (std::size_t lane = 0; lane < 4; ++lane) v_[lane] = mixRound(v_[lane], readLE64(p + lane * 8));
    }

    std::array<std::uint64_t, 4> v_{kP1 + kP2, kP2, 0, 0 - kP1};
    std::array<std::uint8_t, kStripe> buffer_{};
    std::size_t bufferSize_ = 0;
    std::uint64_t totalLength_ = 0;
};

std::string hashFileContents(const fs::path& path) {
    std::ifstream in(path, std::ios::binary);
    if (!in) throw std::runtime_error("cannot open '" + path.string() + "'");
    std::vector<char> chunk(std::size_t{1} << 20);
    Xxh64 hasher;
    while (in) {
        in.read(chunk.data(), static_cast<std::streamsize>(chunk.size()));
        const std::streamsize got = in.gcount();
        if (got > 0) hasher.update(reinterpret_cast<const std::uint8_t*>(chunk.data()), static_cast<std::size_t>(got));
    }
    if (in.bad()) throw std::runtime_error("read error while hashing '" + path.string() + "'");
    char hex[17];
    std::snprintf(hex, sizeof hex, "%016llx", static_cast<unsigned long long>(hasher.digest()));
    return std::string("xxh64:") + hex;
}

// -----------------------------------------------------------------------------
// Image probing: dimensions plus EXIF from TIFF-based RAW (DNG, CR2, NEF, ARW,
// ORF, RW2, PEF...), JPEG and PNG. This baseline reader is enough to populate
// the catalog. Formats it does not recognise (CR3, HEIF, RAF) still import,
// just without metadata. Full RAW decoding belongs to the develop pipeline.
// -----------------------------------------------------------------------------

struct ProbeResult {
    std::uint32_t width = 0;
    std::uint32_t height = 0;
    std::optional<std::int64_t> dateCaptured;
    AssetMetadata metadata;
};

using detail::RandomAccessFile;
using detail::readBE16;
using detail::readBE32;
using detail::TiffReader;

constexpr std::int64_t daysFromCivil(std::int64_t y, unsigned m, unsigned d) {
    y -= m <= 2;
    const std::int64_t era = (y >= 0 ? y : y - 399) / 400;
    const auto yoe = static_cast<unsigned>(y - era * 400);
    const unsigned doy = (153 * (m > 2 ? m - 3 : m + 9) + 2) / 5 + d - 1;
    const unsigned doe = yoe * 365 + yoe / 4 - yoe / 100 + doy;
    return era * 146097 + static_cast<std::int64_t>(doe) - 719468;
}

// "YYYY:MM:DD HH:MM:SS" with an optional EXIF 2.31 offset such as "+02:00".
std::optional<std::int64_t> parseExifDateTime(std::string_view text, std::optional<std::string_view> utcOffset) {
    if (text.size() < 19) return std::nullopt;
    auto number = [&](std::string_view s, std::size_t pos, std::size_t len) -> std::optional<int> {
        int value = 0;
        for (std::size_t i = pos; i < pos + len; ++i) {
            if (i >= s.size() || !std::isdigit(static_cast<unsigned char>(s[i]))) return std::nullopt;
            value = value * 10 + (s[i] - '0');
        }
        return value;
    };
    const auto year = number(text, 0, 4), month = number(text, 5, 2), day = number(text, 8, 2);
    const auto hour = number(text, 11, 2), minute = number(text, 14, 2), second = number(text, 17, 2);
    if (!year || !month || !day || !hour || !minute || !second) return std::nullopt;
    // Cameras without a set clock write "0000:00:00 00:00:00".
    if (*year < 1800 || *month < 1 || *month > 12 || *day < 1 || *day > 31 || *hour > 23 || *minute > 59 ||
        *second > 60) {
        return std::nullopt;
    }
    std::int64_t seconds = daysFromCivil(*year, static_cast<unsigned>(*month), static_cast<unsigned>(*day)) * 86400 +
                           *hour * 3600 + *minute * 60 + *second;
    if (utcOffset && utcOffset->size() >= 6 && ((*utcOffset)[0] == '+' || (*utcOffset)[0] == '-')) {
        const auto offHours = number(*utcOffset, 1, 2), offMinutes = number(*utcOffset, 4, 2);
        if (offHours && offMinutes) {
            const int sign = (*utcOffset)[0] == '-' ? -1 : 1;
            seconds -= sign * (*offHours * 3600 + *offMinutes * 60);
        }
    }
    return seconds;
}

ProbeResult probeTiff(RandomAccessFile& file, std::uint64_t base) {
    ProbeResult result;
    TiffReader tiff(file, base);
    if (!tiff.parseHeader()) return result;

    // RAW containers keep several images (thumbnail, preview, full-resolution
    // sensor data) in chained IFDs and SubIFDs. Report the largest one.
    std::uint64_t bestArea = 0;
    auto considerDimensions = [&](std::uint32_t w, std::uint32_t h) {
        const std::uint64_t area = std::uint64_t{w} * h;
        if (area > bestArea) {
            bestArea = area;
            result.width = w;
            result.height = h;
        }
    };
    auto dimensionsOf = [&](const std::vector<TiffReader::Entry>& entries) {
        std::uint32_t w = 0, h = 0;
        for (const auto& e : entries) {
            if (e.tag == 0x0100) w = tiff.readUInt(e).value_or(0);
            if (e.tag == 0x0101) h = tiff.readUInt(e).value_or(0);
        }
        considerDimensions(w, h);
    };

    std::optional<std::uint32_t> exifIfd, gpsIfd;
    std::vector<std::uint32_t> subIfds;
    std::optional<std::string> dateTimeFallback;
    std::set<std::uint32_t> visited;  // guards against cyclic IFD chains in corrupt files
    std::vector<TiffReader::Entry> entries;

    std::uint32_t offset = tiff.firstIfdOffset();
    for (int index = 0; offset != 0 && index < 8 && visited.insert(offset).second; ++index) {
        std::uint32_t next = 0;
        if (!tiff.readIfd(offset, entries, next)) break;
        dimensionsOf(entries);
        for (const auto& e : entries) {
            switch (e.tag) {
            case 0x010F: if (!result.metadata.cameraMake) result.metadata.cameraMake = tiff.readAscii(e); break;
            case 0x0110: if (!result.metadata.cameraModel) result.metadata.cameraModel = tiff.readAscii(e); break;
            case 0x0132: if (!dateTimeFallback) dateTimeFallback = tiff.readAscii(e); break;
            case 0x8769: if (!exifIfd) exifIfd = tiff.readUInt(e); break;
            case 0x8825: if (!gpsIfd) gpsIfd = tiff.readUInt(e); break;
            case 0x014A:
                for (std::uint32_t i = 0; i < std::min<std::uint32_t>(e.count, 8); ++i) {
                    if (auto sub = tiff.readUInt(e, i)) subIfds.push_back(*sub);
                }
                break;
            default: break;
            }
        }
        offset = next;
    }

    for (const std::uint32_t sub : subIfds) {
        std::uint32_t ignored = 0;
        if (visited.insert(sub).second && tiff.readIfd(sub, entries, ignored)) dimensionsOf(entries);
    }

    std::optional<std::string> dateTimeOriginal, offsetTimeOriginal;
    std::uint32_t unusedNext = 0;
    if (exifIfd && tiff.readIfd(*exifIfd, entries, unusedNext)) {
        std::uint32_t pixelX = 0, pixelY = 0;
        AssetMetadata& m = result.metadata;
        for (const auto& e : entries) {
            switch (e.tag) {
            case 0x829A: m.shutterSpeed = tiff.readRational(e); break;
            case 0x829D: m.aperture = tiff.readRational(e); break;
            case 0x8827:
                if (auto iso = tiff.readUInt(e); iso && *iso > 0) m.iso = static_cast<std::int32_t>(*iso);
                break;
            case 0x9003: dateTimeOriginal = tiff.readAscii(e); break;
            case 0x9011: offsetTimeOriginal = tiff.readAscii(e); break;
            case 0x920A: m.focalLength = tiff.readRational(e); break;
            case 0xA002: pixelX = tiff.readUInt(e).value_or(0); break;
            case 0xA003: pixelY = tiff.readUInt(e).value_or(0); break;
            case 0xA434: m.lens = tiff.readAscii(e); break;
            default: break;
            }
        }
        considerDimensions(pixelX, pixelY);
        // The schema rejects non-positive values; treat them as "not recorded".
        auto positiveOrNull = [](std::optional<double>& v) {
            if (v && !(*v > 0.0)) v.reset();
        };
        positiveOrNull(m.shutterSpeed);
        positiveOrNull(m.aperture);
        positiveOrNull(m.focalLength);
    }

    if (gpsIfd && tiff.readIfd(*gpsIfd, entries, unusedNext)) {
        std::optional<std::string> latRef, lonRef;
        std::optional<double> lat, lon;
        auto degrees = [&](const TiffReader::Entry& e) -> std::optional<double> {
            const auto d = tiff.readRational(e, 0), m = tiff.readRational(e, 1), s = tiff.readRational(e, 2);
            if (!d || !m || !s) return std::nullopt;
            return *d + *m / 60.0 + *s / 3600.0;
        };
        for (const auto& e : entries) {
            switch (e.tag) {
            case 0x0001: latRef = tiff.readAscii(e); break;
            case 0x0002: lat = degrees(e); break;
            case 0x0003: lonRef = tiff.readAscii(e); break;
            case 0x0004: lon = degrees(e); break;
            default: break;
            }
        }
        if (lat && lon) {
            if (latRef && (*latRef)[0] == 'S') *lat = -*lat;
            if (lonRef && (*lonRef)[0] == 'W') *lon = -*lon;
            if (*lat >= -90.0 && *lat <= 90.0 && *lon >= -180.0 && *lon <= 180.0) {
                result.metadata.gpsLatitude = lat;
                result.metadata.gpsLongitude = lon;
            }
        }
    }

    if (dateTimeOriginal) {
        result.dateCaptured = parseExifDateTime(*dateTimeOriginal, offsetTimeOriginal);
    }
    if (!result.dateCaptured && dateTimeFallback) {
        result.dateCaptured = parseExifDateTime(*dateTimeFallback, std::nullopt);
    }
    return result;
}

ProbeResult probeJpeg(RandomAccessFile& file) {
    ProbeResult result;
    std::optional<ProbeResult> exif;
    std::uint32_t frameWidth = 0, frameHeight = 0;
    std::uint64_t pos = 2;  // after SOI
    while (pos + 4 <= file.size()) {
        std::uint8_t header[4];
        if (!file.read(pos, header, sizeof header) || header[0] != 0xFF) break;
        const std::uint8_t marker = header[1];
        if (marker == 0xFF) {  // fill byte
            ++pos;
            continue;
        }
        if (marker == 0x01 || (marker >= 0xD0 && marker <= 0xD8)) {  // markers without a length
            pos += 2;
            continue;
        }
        if (marker == 0xD9 || marker == 0xDA) break;  // EOI / start of scan: no more headers
        const std::uint16_t length = readBE16(header + 2);
        if (length < 2) break;

        if (marker == 0xE1 && !exif && length >= 8) {
            std::uint8_t id[6];
            if (file.read(pos + 4, id, sizeof id) && std::memcmp(id, "Exif\0\0", 6) == 0) {
                exif = probeTiff(file, pos + 10);
            }
        }
        const bool startOfFrame = marker >= 0xC0 && marker <= 0xCF && marker != 0xC4 && marker != 0xC8 &&
                                  marker != 0xCC;
        if (startOfFrame && length >= 7) {
            std::uint8_t sof[5];
            if (file.read(pos + 4, sof, sizeof sof)) {
                frameHeight = readBE16(sof + 1);
                frameWidth = readBE16(sof + 3);
            }
        }
        pos += 2 + std::uint64_t{length};
    }
    if (exif) result = std::move(*exif);
    if (frameWidth > 0 && frameHeight > 0) {  // the coded frame beats EXIF
        result.width = frameWidth;
        result.height = frameHeight;
    }
    return result;
}

ProbeResult probeImageFile(const fs::path& path) {
    RandomAccessFile file(path);
    std::uint8_t magic[24] = {};
    if (!file.read(0, magic, std::min<std::uint64_t>(sizeof magic, file.size()))) return {};

    if (magic[0] == 0xFF && magic[1] == 0xD8 && magic[2] == 0xFF) return probeJpeg(file);
    if ((magic[0] == 'I' && magic[1] == 'I') || (magic[0] == 'M' && magic[1] == 'M')) return probeTiff(file, 0);

    static constexpr std::uint8_t kPngSignature[8] = {0x89, 'P', 'N', 'G', 0x0D, 0x0A, 0x1A, 0x0A};
    if (std::memcmp(magic, kPngSignature, 8) == 0 && std::memcmp(magic + 12, "IHDR", 4) == 0) {
        ProbeResult result;
        result.width = readBE32(magic + 16);
        result.height = readBE32(magic + 20);
        return result;
    }
    return {};
}

}  // namespace

// -----------------------------------------------------------------------------
// AssetManager
// -----------------------------------------------------------------------------

AssetManager::AssetManager() = default;

AssetManager::~AssetManager() {
    stopWorkers();
    closeDatabases();
}

bool AssetManager::isOpen() const noexcept { return writeDb_ != nullptr; }

void AssetManager::requireOpen() const {
    if (!isOpen()) throw std::logic_error("AssetManager: catalog is not open (call initializeCatalog first)");
}

void AssetManager::initializeCatalog(const std::string& catalogPath) {
    if (isOpen()) throw std::logic_error("AssetManager: catalog already open");
    if (catalogPath.empty() || catalogPath == ":memory:") {
        // The reader and writer are separate connections, so they must share a file.
        throw std::invalid_argument("AssetManager: the catalog must be a file path");
    }

    try {
        const int readWrite = SQLITE_OPEN_READWRITE | SQLITE_OPEN_CREATE | SQLITE_OPEN_NOMUTEX;
        if (sqlite3_open_v2(catalogPath.c_str(), &writeDb_, readWrite, nullptr) != SQLITE_OK) {
            throwSqlite(writeDb_, "open catalog '" + catalogPath + "'");
        }
        sqlite3_extended_result_codes(writeDb_, 1);
        sqlite3_busy_timeout(writeDb_, kBusyTimeoutMs);
        exec(writeDb_, generated::kCatalogSchemaSql);

        {
            Statement mode = prepare(writeDb_, "PRAGMA journal_mode");
            const std::string journal =
                sqlite3_step(mode.get()) == SQLITE_ROW ? columnText(mode.get(), 0).value_or("") : "";
            if (journal != "wal") {
                throw std::runtime_error("catalog requires WAL journaling, but SQLite reports '" + journal + "'");
            }
        }

        const int readOnly = SQLITE_OPEN_READONLY | SQLITE_OPEN_NOMUTEX;
        if (sqlite3_open_v2(catalogPath.c_str(), &readDb_, readOnly, nullptr) != SQLITE_OK) {
            throwSqlite(readDb_, "open catalog read connection");
        }
        sqlite3_extended_result_codes(readDb_, 1);
        sqlite3_busy_timeout(readDb_, kBusyTimeoutMs);
        sqlite3_set_authorizer(readDb_, &readOnlyAuthorizer, nullptr);
    } catch (...) {
        closeDatabases();
        throw;
    }

    const unsigned workerCount = std::clamp(std::thread::hardware_concurrency(), 2u, 8u);
    {
        std::lock_guard lock(queueMutex_);
        stopping_ = false;
    }
    for (unsigned i = 0; i < workerCount; ++i) workers_.emplace_back([this] { workerLoop(); });
}

void AssetManager::workerLoop() {
    for (;;) {
        std::packaged_task<AssetRecord()> task;
        {
            std::unique_lock lock(queueMutex_);
            queueCv_.wait(lock, [this] { return stopping_ || !importQueue_.empty(); });
            if (stopping_) return;
            task = std::move(importQueue_.front());
            importQueue_.pop_front();
        }
        task();  // packaged_task stores any exception in the future
    }
}

void AssetManager::stopWorkers() noexcept {
    {
        std::lock_guard lock(queueMutex_);
        stopping_ = true;
    }
    queueCv_.notify_all();
    for (auto& worker : workers_) {
        if (worker.joinable()) worker.join();
    }
    workers_.clear();
    std::lock_guard lock(queueMutex_);
    importQueue_.clear();  // abandoned futures report broken_promise
}

void AssetManager::closeDatabases() noexcept {
    if (readDb_) sqlite3_close_v2(readDb_);
    if (writeDb_) sqlite3_close_v2(writeDb_);
    readDb_ = nullptr;
    writeDb_ = nullptr;
}

std::future<AssetRecord> AssetManager::importFile(const std::string& absolutePath) {
    requireOpen();
    if (!fs::path(absolutePath).is_absolute()) {
        throw std::invalid_argument("importFile requires an absolute path, got '" + absolutePath + "'");
    }
    std::packaged_task<AssetRecord()> task([this, absolutePath] { return importFileBlocking(absolutePath); });
    std::future<AssetRecord> result = task.get_future();
    {
        std::lock_guard lock(queueMutex_);
        if (stopping_) throw std::logic_error("AssetManager is shutting down");
        importQueue_.push_back(std::move(task));
    }
    queueCv_.notify_one();
    return result;
}

AssetRecord AssetManager::importFileBlocking(const std::string& absolutePath) {
    const fs::path path(absolutePath);
    std::error_code ec;
    if (!fs::is_regular_file(path, ec)) throw std::runtime_error("not a regular file: '" + absolutePath + "'");

    // Expensive, lock-free phase. Runs on several workers at once.
    std::string fileHash = hashFileContents(path);
    ProbeResult probe = probeImageFile(path);

    std::lock_guard lock(writeMutex_);
    if (auto existing = findByHashLocked(fileHash)) return std::move(*existing);

    AssetRecord record;
    record.id = generateUuidV4();
    record.filePath = path.string();
    record.fileName = path.filename().string();
    record.fileHash = std::move(fileHash);
    record.dateCaptured = probe.dateCaptured;
    record.dateImported = nowUnixSeconds();
    record.width = probe.width;
    record.height = probe.height;
    record.metadata = std::move(probe.metadata);

    Transaction transaction(writeDb_);
    {
        Statement s = prepare(writeDb_,
                              "INSERT INTO assets (id, file_path, file_name, file_hash, date_captured, date_imported,"
                              " width, height, rating, color_label, flag)"
                              " VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10, ?11)");
        bindText(s.get(), 1, record.id);
        bindText(s.get(), 2, record.filePath);
        bindText(s.get(), 3, record.fileName);
        bindText(s.get(), 4, record.fileHash);
        bindOptional(s.get(), 5, record.dateCaptured);
        bindInt64(s.get(), 6, record.dateImported);
        bindInt64(s.get(), 7, record.width);
        bindInt64(s.get(), 8, record.height);
        bindInt64(s.get(), 9, record.rating);
        bindInt64(s.get(), 10, static_cast<std::int64_t>(record.colorLabel));
        bindInt64(s.get(), 11, static_cast<std::int64_t>(record.flag));
        stepDone(s.get(), writeDb_, "insert asset");
    }
    {
        const AssetMetadata& m = record.metadata;
        Statement s = prepare(writeDb_,
                              "INSERT INTO metadata (asset_id, camera_make, camera_model, lens, iso, focal_length,"
                              " aperture, shutter_speed, gps_latitude, gps_longitude)"
                              " VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10)");
        bindText(s.get(), 1, record.id);
        bindOptional(s.get(), 2, m.cameraMake);
        bindOptional(s.get(), 3, m.cameraModel);
        bindOptional(s.get(), 4, m.lens);
        bindOptional(s.get(), 5, m.iso);
        bindOptional(s.get(), 6, m.focalLength);
        bindOptional(s.get(), 7, m.aperture);
        bindOptional(s.get(), 8, m.shutterSpeed);
        bindOptional(s.get(), 9, m.gpsLatitude);
        bindOptional(s.get(), 10, m.gpsLongitude);
        stepDone(s.get(), writeDb_, "insert metadata");
    }
    transaction.commit();
    return record;
}

std::optional<AssetRecord> AssetManager::findByHashLocked(const std::string& fileHash) {
    Statement s = prepare(writeDb_, std::string(kAssetSelect) + " WHERE a.file_hash = ?1");
    bindText(s.get(), 1, fileHash);
    const int rc = sqlite3_step(s.get());
    if (rc == SQLITE_ROW) return readAssetRow(s.get());
    if (rc != SQLITE_DONE) throwSqlite(writeDb_, "find asset by hash");
    return std::nullopt;
}

std::vector<AssetRecord> AssetManager::queryAssets(const std::string& sqlFilter,
                                                   const std::vector<QueryParam>& params) const {
    requireOpen();
    std::string sql(kAssetSelect);
    if (!isBlank(sqlFilter)) {
        // Newlines keep a trailing "--" comment in the filter from swallowing the ")".
        sql += " WHERE (\n";
        sql += sqlFilter;
        sql += "\n)";
    }
    sql += " ORDER BY a.date_captured IS NULL, a.date_captured DESC, a.file_name, a.id";

    std::lock_guard lock(readMutex_);
    Statement s = prepare(readDb_, sql);
    const int expected = sqlite3_bind_parameter_count(s.get());
    if (expected != static_cast<int>(params.size())) {
        throw std::invalid_argument("queryAssets: filter expects " + std::to_string(expected) + " parameter(s), got " +
                                    std::to_string(params.size()));
    }
    for (std::size_t i = 0; i < params.size(); ++i) {
        const int index = static_cast<int>(i) + 1;
        std::visit(Overloaded{
                       [&](std::monostate) { bindNull(s.get(), index); },
                       [&](std::int64_t v) { bindInt64(s.get(), index, v); },
                       [&](double v) { bindDouble(s.get(), index, v); },
                       [&](const std::string& v) { bindText(s.get(), index, v); },
                   },
                   params[i].value);
    }

    std::vector<AssetRecord> results;
    int rc;
    while ((rc = sqlite3_step(s.get())) == SQLITE_ROW) results.push_back(readAssetRow(s.get()));
    if (rc != SQLITE_DONE) throwSqlite(readDb_, "queryAssets");
    return results;
}

std::optional<AssetRecord> AssetManager::getAsset(const std::string& assetId) const {
    auto results = queryAssets("a.id = ?", {assetId});
    if (results.empty()) return std::nullopt;
    return std::move(results.front());
}

bool AssetManager::updateIntegerColumn(const char* sql, const std::string& assetId, std::int64_t value) {
    requireOpen();
    std::lock_guard lock(writeMutex_);
    Statement s = prepare(writeDb_, sql);
    bindInt64(s.get(), 1, value);
    bindText(s.get(), 2, assetId);
    stepDone(s.get(), writeDb_, "update asset");
    return sqlite3_changes(writeDb_) > 0;
}

bool AssetManager::updateAssetRating(const std::string& assetId, int rating) {
    if (rating < 0 || rating > 5) throw std::invalid_argument("rating must be in [0, 5]");
    return updateIntegerColumn("UPDATE assets SET rating = ?1 WHERE id = ?2", assetId, rating);
}

bool AssetManager::updateAssetFlag(const std::string& assetId, AssetFlag flag) {
    const auto value = static_cast<std::int64_t>(flag);
    if (value < -1 || value > 1) throw std::invalid_argument("flag must be -1, 0 or 1");
    return updateIntegerColumn("UPDATE assets SET flag = ?1 WHERE id = ?2", assetId, value);
}

bool AssetManager::updateAssetColorLabel(const std::string& assetId, ColorLabel label) {
    const auto value = static_cast<std::int64_t>(label);
    if (value < 0 || value > 5) throw std::invalid_argument("color label must be in [0, 5]");
    return updateIntegerColumn("UPDATE assets SET color_label = ?1 WHERE id = ?2", assetId, value);
}

void AssetManager::saveEditStack(const std::string& assetId, const std::vector<EditNodeRecord>& nodes) {
    requireOpen();
    std::lock_guard lock(writeMutex_);
    Transaction transaction(writeDb_);
    {
        Statement s = prepare(writeDb_, "DELETE FROM edit_nodes WHERE asset_id = ?1");
        bindText(s.get(), 1, assetId);
        stepDone(s.get(), writeDb_, "clear edit stack");
    }
    Statement insert = prepare(writeDb_,
                               "INSERT INTO edit_nodes (asset_id, node_index, node_type, serialized_params)"
                               " VALUES (?1, ?2, ?3, ?4)");
    for (const EditNodeRecord& node : nodes) {
        sqlite3_reset(insert.get());
        bindText(insert.get(), 1, assetId);
        bindInt64(insert.get(), 2, node.nodeIndex);
        bindText(insert.get(), 3, node.nodeType);
        bindBlob(insert.get(), 4, node.serializedParams);
        stepDone(insert.get(), writeDb_, "insert edit node");  // FK violation if the asset does not exist
    }
    transaction.commit();
}

std::vector<EditNodeRecord> AssetManager::loadEditStack(const std::string& assetId) const {
    requireOpen();
    std::lock_guard lock(readMutex_);
    Statement s = prepare(readDb_,
                          "SELECT node_index, node_type, serialized_params FROM edit_nodes"
                          " WHERE asset_id = ?1 ORDER BY node_index");
    bindText(s.get(), 1, assetId);
    std::vector<EditNodeRecord> nodes;
    int rc;
    while ((rc = sqlite3_step(s.get())) == SQLITE_ROW) {
        EditNodeRecord node;
        node.nodeIndex = sqlite3_column_int(s.get(), 0);
        node.nodeType = columnText(s.get(), 1).value_or("");
        const auto* blob = static_cast<const std::byte*>(sqlite3_column_blob(s.get(), 2));
        const int size = sqlite3_column_bytes(s.get(), 2);
        if (blob && size > 0) node.serializedParams.assign(blob, blob + size);
        nodes.push_back(std::move(node));
    }
    if (rc != SQLITE_DONE) throwSqlite(readDb_, "loadEditStack");
    return nodes;
}

}  // namespace darkhouse
